
#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
[package]
name = "zenoh-perf-latency"
version = "0.10.0-dev"
repository = "https://github.com/eclipse-zenoh/zenoh"
homepage = "http://zenoh.io"
authors = ["kydos <angelo@icorsaro.net>",
           "Julien Enoch <julien@enoch.fr>",
           "Olivier Hécart <olivier.hecart@adlinktech.com>",
           "Luca Cominardi <luca.cominardi@adlinktech.com>"]
edition = "2021"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh: Zero Overhead Pub/sub, Store/Query and Compute."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
async-std            = { workspace = true }
async-trait          = { workspace = true }
clap                 = { workspace = true }
env_logger           = { workspace = true }
json5                = { workspace = true }
log                  = { workspace = true }
rand                 = { workspace = true }
slab                 = { workspace = true }
zenoh                = { workspace = true, features = ["transport_shm", "shared-memory"] }
zenoh-buffers        = { workspace = true }
zenoh-codec          = { workspace = true }
zenoh-core           = { workspace = true }
zenoh-link           = { workspace = true }
zenoh-protocol       = { workspace = true }
zenoh-transport      = { workspace = true }
zenoh-util           = { workspace = true }
