#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
name: Push

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macOS, windows-11]

    steps:
    - uses: actions/checkout@v2

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

    - name: Code format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings
